### ISSUE TITLE
Use go-swagger to automatically generate testing clients

### ISSUE THREAD

**Issue by xiaolanz** [istio/old_broker_repo#11]
https://github.com/cloudfoundry-incubator/cf-swagger @ayj

**Comment by sakshigoel12** [comment]
@xiaolanz is this 0.2 blocking? If yes please add an ETA otherwise move it to the next release

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1487](https://github.com/istio/istio/issues/1487) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1488](https://github.com/istio/istio/issues/1488) via [**ZenHub**](https://www.zenhub.com/)
